// Generated by CoffeeScript 1.6.3
(function() {
  var getLocation, showPosition;

  $(function() {
    var name;
    name = prompt("What is your name");
    document.write(name);
    return $('#send-current-location').click(function() {
      return getLocation();
    });
  });

  getLocation = function() {
    if (navigator.geolocation) {
      return navigator.geolocation.getCurrentPosition(showPosition);
    } else {
      return alert('GPS not enabled on device.');
    }
  };

  showPosition = function(position) {
    var latitude, longitude;
    latitude = position.coords.latitude;
    longitude = position.coords.longitude;
    return $('#map').goMap({
      latitude: latitude,
      longitude: longitude,
      zoom: 16,
      maptype: 'ROADMAP',
      markers: [
        {
          latitude: latitude,
          longitude: longitude,
          title: 'Current Location',
          html: {
            content: '<p>Latitude: ' + latitude + '</p><p>Longitude: ' + longitude + '</p>',
            popup: false
          }
        }
      ]
    });
  };

}).call(this);
