// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $('#go').on('click', function() {
      return $.ajax({
        type: 'POST',
        url: "http://radiocollarapp.herokuapp.com/api/v1/sessions",
        data: {
          "email": $('#email').val(),
          "password": $('#password').val()
        },
        dataType: "json",
        success: function(data) {
          window.token = $.parseJSON(responseData.responseText).token;
          $.ajaxSetup({
            headers: {
              "auth_token": window.token
            }
          });
          $('#content').empty();
          return window.location = '#home';
        },
        error: function(responseData) {
          return alert($.parseJSON(responseData.responseText).errors);
        }
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=auth.map
*/
